---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript:
          mass_threshold: 45
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- spec/lib/
