language: node_js

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: grunt test

after_script:
  - npm install grunt-karma-coveralls && grunt coveralls
