language: node_js
node_js:
  - 8

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - grunt test

after_success:
  - grunt release --release-username=$RELEASE_USERNAME --release-password=$RELEASE_PASSWORD

after_script:
  - grunt coveralls
